# Generated by Django 6.0.7 on 2026-07-24 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_saved', models.FloatField(default=0.0)),
                ('waste_diverted', models.FloatField(default=0.0)),
                ('food_saved', models.FloatField(default=0.0)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
