apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoverzz-postgres
  namespace: ecoverzz-prod
  labels:
    app: ecoverzz
    tier: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecoverzz
      tier: postgres
  template:
    metadata:
      labels:
        app: ecoverzz
        tier: postgres
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:15-3.3-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: ecoverzz-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "eco_user"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "eco_user"]
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "512Mi"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
