apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoverzz-frontend
  namespace: ecoverzz-prod
  labels:
    app: ecoverzz
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecoverzz
      tier: frontend
  template:
    metadata:
      labels:
        app: ecoverzz
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: eco_frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: ecoverzz-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "150m"
              memory: "128Mi"
      imagePullSecrets: []
