apiVersion: v1
kind: Secret
metadata:
  name: ecoverzz-secret
  namespace: ecoverzz-prod
  labels:
    app: ecoverzz
type: Opaque
stringData:
  POSTGRES_PASSWORD: eco_pass
  RABBITMQ_PASSWORD: eco_pass
  MINIO_SECRET_KEY: minioadmin
  JWT_SECRET_KEY: change_this_to_a_strong_secret
