# Generated by Django 6.0.7 on 2026-07-22 16:57

import django.db.models.deletion
import food.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('food_type', models.CharField(choices=[('COOKED', 'Cooked Meals'), ('PACKAGED', 'Packaged Food'), ('RAW_INGREDIENTS', 'Raw Ingredients'), ('FRUITS_VEG', 'Fruits & Vegetables'), ('OTHER', 'Other')], default='COOKED', max_length=20)),
                ('quantity', models.CharField(help_text="E.g. '10 kg', '20 plates', '5 boxes'", max_length=100)),
                ('quality_status', models.CharField(choices=[('EXCELLENT', 'Excellent (Freshly made / Long shelf life)'), ('GOOD', 'Good (Safe to consume, short shelf life)'), ('FAIR', 'Fair (Must consume immediately)')], default='GOOD', max_length=20)),
                ('expiry_time', models.DateTimeField(validators=[food.validators.validate_expiry_time])),
                ('pickup_address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Claim'), ('ACCEPTED', 'Claimed by NGO'), ('ASSIGNED', 'Assigned to Volunteer'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ngo_claimed_donations', to=settings.AUTH_USER_MODEL)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_pickup_donations', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDonationTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Claim'), ('ACCEPTED', 'Claimed by NGO'), ('ASSIGNED', 'Assigned to Volunteer'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='food.fooddonation')),
            ],
        ),
    ]
