# Generated by Django 6.0.7 on 2026-07-24 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='qr_code_token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=64),
        ),
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity_needed', models.CharField(max_length=100)),
                ('food_type', models.CharField(choices=[('COOKED', 'Cooked Meals'), ('PACKAGED', 'Packaged Food'), ('RAW_INGREDIENTS', 'Raw Ingredients'), ('FRUITS_VEG', 'Fruits & Vegetables'), ('OTHER', 'Other')], default='COOKED', max_length=20)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_food_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
