# Generated by Django 6.0.7 on 2026-07-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_collectioncenter_wastepickuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='report_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
